{% set name = "scine-sparrow-python" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/sparrow/archive/refs/tags/{{ version }}.tar.gz
    sha256: 439b79b5ce1e59c78dee85157839fcb5e6f9bdba8f79cdaa336035869b4f55b4

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - scine-sparrow {{ version }}
  run:
    - python >=3.6
    - scine-sparrow {{ version }}
    - scine-utilities-python

test:
  imports:
    - scine_sparrow
  source_files:
    - src/Sparrow/Python/Tests/
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest src/Sparrow/Python/Tests/*.py

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Sparrow is a code for fast semiempirical quantum chemical calculations (Python bindings)
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/sparrow

extra:
  recipe-maintainers:
    - awvwgk
